const COURSES=[
['BIO 180','Introduction to Biology I','BIO',3,'Core',3.0,3],['BIO 180L','Introduction to Biology I Lab','BIO',1,'Helpful',2.4,2],['BIO 181','Introduction to Biology II','BIO',3,'Core',3.2,4],['BIO 181L','Introduction to Biology II Lab','BIO',1,'Helpful',2.6,2],['BIO 199','Biology Orientation','BIO',1,'Not Tested',1.4,1],['BIO 221','General Microbiology','BIO',3,'Helpful',3.3,5],['BIO 240','Neurobiology','BIO',4,'Helpful',3.6,6],['BIO 321','Biology of Microorganisms','BIO',4,'Helpful',3.7,7],['BIO 375','Genetics & Molecular Biology','BIO',3,'Core',3.8,7],['BIO 378','Cell and Molecular Biology','BIO',3,'Core',3.9,7],['BIO 380','Histology with Lab','BIO',4,'Low Connection',3.6,7],['BIO 381','Pathophysiology','BIO',3,'Helpful',3.8,6],['BIO 383','Human Embryology','BIO',3,'Low Connection',3.4,5],['BIO 385','Principles of Biochemistry','BIO',4,'Core',4.1,8],['BIO 410','Immunology','BIO',3,'Helpful',3.8,6],['BIO 411','Medical Microbiology','BIO',4,'Low Connection',4.0,8],['BIO 412','Virology','BIO',3,'Low Connection',3.7,6],['BIO 430','Principles of Pharmacology','BIO',3,'Low Connection',4.0,7],['BIO 480','Human Anatomy with Lab','BIO',4,'Helpful',4.3,10],['BIO 481','Principles of Physiology','BIO',5,'Helpful',4.2,10],['BIO 482','Head and Neck Anatomy','BIO',2,'Not Tested',3.8,5],['BIO 490','Advanced Neuroscience','BIO',4,'Not Tested',4.2,8],
['CHEM 105','General Chemistry I','CHEM',3,'Core',3.1,5],['CHEM 105L','General Chemistry Lab I','CHEM',1,'Helpful',2.4,3],['CHEM 106','General Chemistry II','CHEM',3,'Core',3.3,6],['CHEM 106L','General Chemistry Lab II','CHEM',1,'Helpful',2.5,3],['CHEM 351','Organic Chemistry I','CHEM',3,'Core',4.1,8],['CHEM 351L','Organic Chemistry Lab I','CHEM',1,'Helpful',3.1,4],['CHEM 352','Organic Chemistry II','CHEM',3,'Helpful',4.2,8],['CHEM 352L','Organic Chemistry Lab II','CHEM',1,'Helpful',3.2,4],['CHEM 481','Biochemistry I','CHEM',3,'Core',4.2,8],['CHEM 482','Biochemistry II','CHEM',3,'Low Connection',4.0,7],
['PH 105','Intro Applied Physics I','PH',4,'Core',3.5,7],['PH 106','Intro Applied Physics II','PH',4,'Core',3.7,8],['MATH 112X','Calculus I','MATH',4,'Not Tested',3.5,7],['MATH 221B','Biostatistics','MATH',3,'Low Connection',3.0,5],['PSYCH 111','General Psychology','SOC',3,'Core',2.3,4],['SOC 111','Introduction to Sociology','SOC',3,'Core',2.2,4],['PSYCH 342','Abnormal Psychology','SOC',3,'Low Connection',2.8,4],['HCA 280','Healthcare Law and Ethics','SOC',2,'Not Tested',2.1,3]
].map(x=>({id:x[0],title:x[1],subject:x[2],credits:x[3],mcat:x[4],difficulty:x[5],workload:x[6],offered:'Verify current offering',prereq:'Verify with current BYU-Idaho catalog',desc:`${x[1]} is included in this independent student-built pre-med guide. Verify official course details, prerequisites, and availability with the current BYU-Idaho catalog before registration.`}));
const SUBJECTS={BIO:'Biology',CHEM:'Chemistry',PH:'Physics',MATH:'Math & Statistics',SOC:'Behavioral & Social'};
const ICONS={book:'<svg viewBox="0 0 24 24"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H11v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Zm16 0A2.5 2.5 0 0 0 17.5 3H13v16h4.5a2.5 2.5 0 0 1 2.5 2.5v-16Z"/></svg>',calendar:'<svg viewBox="0 0 24 24"><path d="M7 2v3m10-3v3M3 9h18M5 4h14a2 2 0 0 1 2 2v15H3V6a2 2 0 0 1 2-2Z"/></svg>',shield:'<svg viewBox="0 0 24 24"><path d="M12 3 20 6v6c0 5-3.4 8-8 9-4.6-1-8-4-8-9V6l8-3Z"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',chart:'<svg viewBox="0 0 24 24"><path d="M4 20V10m6 10V4m6 16v-7m4 7H2"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.8 5.7a5.5 5.5 0 0 0-7.8 0L12 6.8l-1.1-1.1a5.5 5.5 0 1 0-7.8 7.8L12 22l8.8-8.5a5.5 5.5 0 0 0 0-7.8Z"/></svg>'};
const icon=n=>`<span class="icon">${ICONS[n]||ICONS.book}</span>`;
const getReviews=()=>JSON.parse(localStorage.getItem('premedV3Reviews')||'[]'); const setReviews=x=>localStorage.setItem('premedV3Reviews',JSON.stringify(x));
const getPlan=()=>JSON.parse(localStorage.getItem('premedV3Plan')||'{}'); const setPlan=x=>localStorage.setItem('premedV3Plan',JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function nav(){return `<header class="topbar"><a class="brand" href="index.html"><span class="brandmark">P</span><span>BYUI Pre-Med</span></a><button class="menu" aria-label="Toggle menu">Menu</button><nav><a href="courses.html">Browse Courses</a><a href="planner.html">Path Planner</a><a href="dashboard.html">Dashboard</a><a href="roadmap.html">Roadmap</a><a class="admin-link" href="admin.html">${icon('shield')} Admin</a></nav></header>`}
function foot(){return `<footer><div><b>BYUI Pre-Med Course Guide</b><span>Built for BYU-Idaho Pre-Med Students</span><small>© 2026 BYUI Pre-Med Course Guide</small></div><div><b>CONTACT & SUPPORT</b><a href="mailto:mgenedavid@gmail.com">mgenedavid@gmail.com</a><small>Independent student-built resource. Not an official BYU-Idaho advising website.</small></div><div><b>MORE</b><a target="_blank" rel="noopener" href="https://www.youtube.com/@RoadToMedSchoolBYU">Road to Med School (BYUI)</a><a href="about.html">About</a><a href="trust.html">Trust & Transparency</a></div></footer>`}
document.querySelectorAll('[data-nav]').forEach(e=>e.innerHTML=nav()); document.querySelectorAll('[data-foot]').forEach(e=>e.innerHTML=foot());
document.querySelectorAll('.menu').forEach(b=>b.onclick=()=>b.closest('.topbar').classList.toggle('open'));
const approved=id=>getReviews().filter(r=>r.course===id&&r.status==='approved');
function avg(rs,k){return rs.length?(rs.reduce((a,r)=>a+(+r[k]||0),0)/rs.length):null}
function courseCard(c){const rs=approved(c.id), d=avg(rs,'difficulty'), w=avg(rs,'workload'), rec=rs.length?Math.round(100*rs.filter(r=>r.recommend).length/rs.length):null;return `<a class="course-card reveal" href="course.html?id=${encodeURIComponent(c.id)}"><div class="course-top"><span class="course-code">${c.id}</span><span class="credits">${c.credits} CR</span></div><h3>${c.title}</h3><span class="mcat ${c.mcat.toLowerCase().replaceAll(' ','-')}"><i></i>${c.mcat}</span><div class="course-metrics">${rs.length?`<span><b>${d.toFixed(1)}/5</b>Difficulty</span><span><b>~${Math.round(w)}h</b>Hrs/wk</span><span><b>${rec}%</b>Recommend</span>`:`<em>No ratings yet</em>`}</div></a>`}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('shown')}),{threshold:.08}); document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
